export const actionTypes = {
    FETCH_SPEAKERS_START: "FETCH_SPEAKERS_START",
    FETCH_SPEAKERS_SUCCESS: "FETCH_SPEAKERS_SUCCESS",
    FETCH_SPEAKERS_FAILED: "FETCH_SPEAKERS_FAILED",
    UPDATE_SPEAKERS_START: "UPDATE_SPEAKERS_START",
    UPDATE_SPEAKERS_SUCCESS: "UPDATE_SPEAKERS_SUCCESS",
    UPDATE_SPEAKERS_FAILED: "UPDATE_SPEAKERS_FAILED",
};