export const actionTypes = {
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_FAILED: "FETCH_FAILED",
    UPDATE_START: "UPDATE_START",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    UPDATE_FAILED: "UPDATE_FAILED",
};